---
name: "mos2_grad"
backend: jax

# raw data source
raw_data:
  type: empad
  path: "~/Downloads/mos2/1/mos2/mos2_0.00_dstep1.0_x64_y64_4DSTEM.raw"
  diff_step: 1.0  # mrad/px
  kv: 120.        # keV

post_load:
 - type: poisson
   scale: 1.0e+6

# initialization

init_probe:
  type: 'focused'
  conv_angle: 25  # mrad
  defocus: 300    # angstrom

init_object: 'random'

init_scan:
  type: 'raster'
  shape: [64, 64] # ny, nx
  step_size: 0.6  # angstrom

# for each reconstruction engine
engines:
   # how to transition from previous state to current reconstruction state
   # how to reconstruct
   # how to output/save
 - type: 'gradient'
   probe_modes: 4
   niter: 100
   grouping: 128

   noise_model:
     type: 'anscombe'
     eps: 0.01

   solvers:
     object:
       type: 'adam'
       learning_rate: 1.0e-2
       nesterov: True
     probe:
       type: 'adam'
       learning_rate: 1.0e-2
       nesterov: True

   regularizers:
     #- type: obj_recip_l1
     #  cost: 1.0e+2
     - type: obj_tv
       cost: 1.0e+0

   iter_constraints:
    - remove_phase_ramp
   group_constraints:
    - type: clamp_object_amplitude
      amplitude: 1.1

   update_probe: {after: 5}
   #update_positions: {after: 30}

   save: {every: 10}
   save_images: {every: 10}
   save_options:
     images: [
      'probe', 'probe_recip', 'object_phase_sum', 'object_mag_sum'
     ]