---
name: "si_grad"
backend: jax

# raw data source
raw_data:
  type: empad
  path: "sample_data/simulated_si/Si_110_Sn_300kV_conv25_defocus15_tds_199.70_dstep0.6.json"

post_load:
 - type: poisson
   scale: 14.46e+6
post_init: []

# initialization

slices:
  n: 10
  total_thickness: 200

# for each reconstruction engine
engines:
   # how to transition from previous state to current reconstruction state
   # how to reconstruct
   # how to output/save
 - type: 'gradient'
   probe_modes: 4
   bwlim_frac: 0.8

   niter: 500
   grouping: 128

   noise_model:
     type: poisson
     eps: 2.0

   solvers:
     object:
       type: 'adam'
       learning_rate: 5.0e-3
       nesterov: True
     probe:
       type: 'adam'
       learning_rate: 0.1
       nesterov: True
     positions:
       type: 'sgd'
       learning_rate: 0.5
       momentum: 0.90
       nesterov: True

   regularizers:
     - type: obj_l2
       cost: 0.4
     - type: obj_tikh
       cost: 0.2
     - type: layers_tikh
       cost: 5.0e+2

   group_constraints: []
   iter_constraints:
     - type: limit_probe_support
       max_angle: 26.0
     - type: clamp_object_amplitude
       amplitude: 1.0

   update_probe: {after: 5}
   update_positions: {after: 5}

   save: {every: 10}
   save_images: {every: 2}
   save_options:
     images: [
      'probe', 'probe_recip', 'object_phase_sum', 'object_mag_sum',
      'object_phase_stack', 'object_mag_stack'
     ]
