---
name: "srtio3_exp"
backend: jax

# raw data source
raw_data:
  type: empad
  path: "~/raw-ptycho/20241123-sto-bicrystal/acq3-pristine/acq3-pristine_calib.json"

# initialization

post_init:
 - drop_nans
 - diffraction_align

slices:
  n: 15
  total_thickness: 200

engines:
 - type: 'gradient'
   sim_shape: [128, 128]
   probe_modes: 4
   niter: 100
   grouping: 128
   bwlim_frac: 1.0

   noise_model:
     type: 'poisson'
     eps: 0.5

   solvers:
     object:
       type: 'adam'
       learning_rate: 5.0e-4
       nesterov: True
     probe:
       type: 'adam'
       learning_rate: 0.1
       nesterov: True
     positions:
       type: 'sgd'
       learning_rate: 0.5
       momentum: 0.99
       nesterov: True

   regularizers:
     - type: obj_l1
       cost: 0.3
     - type: obj_l2
       cost: 0.3
     - type: obj_tikh
       cost: 1.681
     - type: layers_tikh
       cost: 5.0e+3

   group_constraints: []
   iter_constraints:
     - type: limit_probe_support
       max_angle: 26.0
     - type: clamp_object_amplitude
       amplitude: 1.0

   update_probe: {after: 5}
   update_positions: {after: 5}

   save: {every: 10}
   save_images: {every: 5}
   save_options:
     images: [
      'probe', 'probe_recip', 'object_phase_sum', 'object_mag_sum',
      'object_phase_stack', 'object_mag_stack'
     ]

 - type: 'gradient'
   sim_shape: [256, 256]
   probe_modes: 4
   niter: 100
   grouping: 128

   noise_model:
     type: 'poisson'
     eps: 0.5

   solvers:
     object:
       type: 'adam'
       learning_rate: 2.0e-4
       nesterov: True
     probe:
       type: 'adam'
       learning_rate: 0.2
       nesterov: True
     positions:
       type: 'sgd'
       learning_rate: 0.5
       momentum: 0.99
       nesterov: True

   regularizers:
     - type: obj_l1
       cost: 0.145
     - type: obj_l2
       cost: 0.129
     - type: obj_tikh
       cost: 1.681
     - type: layers_tikh
       cost: 5.0e+3

   group_constraints: []
   iter_constraints:
     - type: limit_probe_support
       max_angle: 26.0
     - type: clamp_object_amplitude
       amplitude: 1.0

   update_probe: {after: 5}
   update_positions: {after: 5}

   save: {every: 10}
   save_images: {every: 5}
   save_options:
     images: [
      'probe', 'probe_recip', 'object_phase_sum', 'object_mag_sum',
      'object_phase_stack', 'object_mag_stack'
     ]